#ifndef TOKEN_H
#define TOKEN_H
typedef struct TOKEN_STRUCT {
    enum{
        TOKEN_ID,
        TOKEN_EQUALS,
        TOKEN_STRING,
        TOKEN_SEMI,
        TOKEN_LPAREN,
        TOKEN_RPAREN,
        TOKEN_COMMA,
        TOKEN_LBRACE,
        TOKEN_RBRACE,
        TOKEN_LBRACKET,
        TOKEN_RBRACKET,
        TOKEN_PLUS,
        TOKEN_MINUS,
        TOKEN_MULTIPLY,
        TOKEN_DIVIDE,
        TOKEN_GT,
        TOKEN_LT,
        TOKEN_GTE,
        TOKEN_LTE,
        TOKEN_EQ,
        TOKEN_NEQ,
        TOKEN_AND,
        TOKEN_OR,
        TOKEN_NUMBER,
        TOKEN_FLOAT,
        // Keywords
        TOKEN_BUCKET,
        TOKEN_WHEN_IF,
        TOKEN_WHEN_ELSE,
        TOKEN_WHILE_LOOP,
        TOKEN_FOR_LOOP,
        TOKEN_MAKE_FUNCTION,
        TOKEN_GIVE_BACK,
        TOKEN_SHOW,
        TOKEN_ASK,
        TOKEN_LEN,
        TOKEN_PUSH,
        TOKEN_POP,
        TOKEN_SAFE_DIVIDE,
        TOKEN_ERROR,
        TOKEN_HTTP_GET,
        TOKEN_HTTP_POST,
        TOKEN_DOWNLOAD,
        TOKEN_IS_ONLINE,
        // Math module
        TOKEN_MATH_SQRT,
        TOKEN_MATH_POW,
        TOKEN_MATH_ABS,
        TOKEN_MATH_MAX,
        TOKEN_MATH_MIN,
        TOKEN_MATH_ROUND,
        TOKEN_MATH_RANDOM,
        TOKEN_MATH_RANDOM_RANGE,
        // String module
        TOKEN_STRING_SPLIT,
        TOKEN_STRING_JOIN,
        TOKEN_STRING_REPLACE,
        TOKEN_STRING_TO_UPPER,
        TOKEN_STRING_TO_LOWER,
        TOKEN_STRING_TRIM,
        TOKEN_STRING_CONTAINS,
        TOKEN_STRING_STARTS_WITH,
        // Array module
        TOKEN_ARRAY_FILTER,
        TOKEN_ARRAY_MAP,
        TOKEN_ARRAY_SORT,
        TOKEN_ARRAY_REVERSE,
        TOKEN_ARRAY_UNIQUE,
        TOKEN_ARRAY_FIND,
        TOKEN_ARRAY_SLICE,
        // File module
        TOKEN_FILE_READ,
        TOKEN_FILE_WRITE,
        TOKEN_FILE_EXISTS,
        TOKEN_FILE_DELETE,
        TOKEN_FILE_SIZE,
        // JSON module
        TOKEN_JSON_PARSE,
        TOKEN_JSON_STRINGIFY,
        TOKEN_JSON_GET,
        TOKEN_JSON_SET,
        // Time module
        TOKEN_TIME_NOW,
        TOKEN_TIME_FORMAT,
        TOKEN_TIME_SLEEP,
        // System module
        TOKEN_SYSTEM_RUN,
        TOKEN_SYSTEM_GET_ENV,
        // Import system tokens
        TOKEN_PUTLIB,
        TOKEN_FROM,
        TOKEN_AS,
        TOKEN_STAR,
        TOKEN_YES,
        TOKEN_NO,
        TOKEN_NOTE,
    } type;
    char* value;   
} token_T;
token_T* init_token(int type, char* value);
#endif